### ISSUE TITLE
部署

### ISSUE THREAD

**Issue by BinZhiZhu** [bettershop/LaikeTui#3]
请问有无部署文档？我看你们官网好像没有，没找到，全都是介绍

**Comment by zbyjm6969** [comment]
https://www.laiketui.com/docs/%e4%bd%bf%e7%94%a8%e6%96%87%e6%a1%a3/%e5%ae%89%e8%a3%85%e6%95%99%e7%a8%8b

就是很水就是了

**Comment by PHPXiaoXu** [comment]
> [https://www.laiketui.com/docs/%e4%bd%bf%e7%94%a8%e6%96%87%e6%a1%a3/%e5%ae%89%e8%a3%85% e6％95％99％e7％a8％8b](https://www.laiketui.com/docs/%e4%bd%bf%e7%94%a8%e6%96%87%e6%a1%a3/%e5%ae%89%e8%a3%85%e6%95%99%e7%a8%8b)
> 
> 就是很水就是了

**Comment by PHPXiaoXu** [comment]
这个项目 怎么样！！！

**Comment by BinZhiZhu** [comment]
其实可以前后端分开repo管理的
